name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Amazon EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.141.138.39 << 'EOF'
            cd /var/www/mywebsite/runningCICD
            git pull origin main
            # Jika menggunakan Apache di Amazon Linux
            sudo systemctl restart httpd
          EOF
        env:
          SSH_PRIVATE_ KEY: ${{ secrets.SSH_PRIVATE_KEY }}